#!/usr/bin/env bash

id=$1
stack=$2
stage=$3
app=$4
file=$5

cat >> /var/awslogs/etc/config/$app-$id.conf <<__END__
[$app-$id]
datetime_format = %Y-%m-%d %H:%M:%S
file = $file
initial_position = start_of_file
log_group_name = $stack-$app-$stage
log_stream_name = $stack-$app-$stage-{instance_id}
__END__

systemctl restart awslogs
