version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:30"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/cdk"
    schedule:
      interval: "weekly"
      time: "09:30"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore(deps): "
    # The version of AWS CDK libraries must match those from @guardian/cdk.
    # We'd never be able to update them here independently, so just ignore them.
    ignore:
      - dependency-name: "aws-cdk"
      - dependency-name: "aws-cdk-lib"
      - dependency-name: "constructs"
    labels:
      - "dependencies"
