updatePullRequests = "always"

pullRequests.frequency = "0 0 1 jan,apr,jul,oct ?"

pullRequests.grouping = [
  { name = "non_aws_minor_patch", "title" = "chore(deps): Non-AWS minor and patch version dependency updates", "filter" = [{"version" = "minor"}, {"version" = "patch"}] },
]
