---
- name: Download LATEST Chrome
  get_url: url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb dest=/tmp/google-chrome-stable_amd64.deb
  when: chrome_version is undefined

- name: Download SPECIFIED version of Chrome
  get_url: url=https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_{{chrome_version}}_amd64.deb dest=/tmp/google-chrome-stable_amd64.deb
  when: chrome_version is defined

- name: Install Chrome - ignores errors as expect missing packages
  shell: dpkg -i /tmp/google-chrome-stable_amd64.deb
  ignore_errors: yes

- name: Install missing packages for Chrome
  shell: apt-get install -f -y

- name: Download LATEST Chromedriver
  shell: wget http://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -O /tmp/chromedriver.zip
  when: chromedriver_version is undefined

- name: Download SPECIFIED version of Chromedriver
  shell: wget http://chromedriver.storage.googleapis.com/{{chromedriver_version}}/chromedriver_linux64.zip -O /tmp/chromedriver.zip
  when: chromedriver_version is defined

- name: Unzip Chromedriver
  unarchive: src=/tmp/chromedriver.zip dest=/usr/local/bin/

- name: Enable Chromedriver
  file: path=/usr/local/bin/chromedriver mode=751

