---
- name: Install neo4j GPG signing key
  apt_key: url=https://debian.neo4j.com/neotechnology.gpg.key state=present

- name: Add neo4j repository
  apt_repository: repo='deb https://debian.neo4j.com stable {{ neo4j_repo_version }}' state=present

- name: Install neo4j
  apt:
    name: neo4j={{ neo4j_version}}
    update_cache: yes
