#!/usr/bin/env bash

region=$1
kinesis_stream=$2
file=$3

cat > /etc/aws-kinesis/agent.json <<__END__
{
  "kinesis.endpoint": "kinesis.$region.amazonaws.com",
  "checkpointFile": "/opt/aws-kinesis-agent/run/checkpoints",
  "flows": [
    {
      "filePattern": "$file",
      "initialPosition", "START_OF_FILE",
      "kinesisStream": "$kinesis_stream"
    }
  ]
}
__END__

systemctl restart aws-kinesis-agent
