#!/bin/sh
### BEGIN INIT INFO
# Provides:          set-readahead
# Required-Start:    $local_fs
# Required-Stop:
# X-Start-Before:    mongod mongodb-mms-automation-agent
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Set blockdev readahead
# Description:       Set blockdev readahead, to improve
#                    database performance.
### END INIT INFO

case $1 in
  start)
    for device in `ls /dev/xvd[f-z]`
    do
      /sbin/blockdev --setra 16 ${device}
    done
    ;;
esac
