---
- name: Create target and models directory
  file:
    path: "{{ target_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: Download compiled llama.cpp project
  shell: |
    aws s3 cp s3://amigo-data-{{ model_script_stage.lower() }}/deploy/{{ llama_cpp_build_stage }}/llama-cpp/llama-cpp-cuda.zip /tmp/llama-cpp-cuda.zip
    unzip -o /tmp/llama-cpp-cuda.zip -d {{ target_dir }}

- name: Set ownership of llama directory
  file:
    path: "{{ target_dir }}"
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: Symlink llama-cli into /usr/local/bin
  file:
    src: "{{ target_dir }}/llama.cpp/install/bin/llama-cli"
    dest: /usr/local/bin/llama-cli
    state: link

- name: Symlink llama-server into /usr/local/bin
  file:
    src: "{{ target_dir }}/llama.cpp/install/bin/llama-server"
    dest: /usr/local/bin/llama-server
    state: link


