#!/bin/bash

# Test if master
if [ "$(curl -s 'localhost:9200/_cat/master' | awk '{print $2}')" == "$(hostname)" ]; then

    # Initiate backup
    DATE=$(date +'%Y%m%d%H%M')
    HTTP_CODE=$(curl -s -o /tmp/kibana-backup.log -w '%{http_code}' \
       -XPUT "localhost:9200/_snapshot/s3_backup/kibana_snapshot_${DATE}?pretty" -d '{
         "indices": ".kibana",
         "ignore_unavailable": "true",
         "include_global_state": false
    }')

    if [ $HTTP_CODE -ne 200 ]; then
      cat /tmp/kibana-backup.log
      exit 1
    fi
fi
