---

# NFS
nfs_mount_enabled: False
nfs_mount_id:
nfs_mount_point: /mnt/nfs

## General
airflow_version: 1.10.3
airflow_extra_packages: ['crypto,postgres,google_auth']
airflow_python_path: /usr/bin/python3

airflow_logging_level: "INFO"
airflow_fab_logging_level: "INFO"
airflow_default_timezone: "utc"
airflow_logging_config_class:

airflow_required_libs:
  - python3-dev
  - virtualenv
  - python-pip
  - acl
  - gcc
  - jq
  - libpq-dev

# Owner
airflow_user: airflow
airflow_group: airflow

## Service options
airflow_scheduler_runs: 5

airflow_services:
  airflow-mutex:
    configure: yes
    enabled: no
    state: stopped
  airflow-initdb:
    configure: yes
    enabled: no
    state: stopped
  airflow-webserver:
    configure: yes
    enabled: no
    state: stopped
  airflow-scheduler:
    configure: yes
    enabled: no
    state: stopped
  airflow-worker:
    configure: no
    enabled: no
    state: stopped
  airflow-connections-update:
    configure: yes
    enabled: no
    state: stopped
  airflow-dags-update:
    configure: yes
    enabled: no
    state: stopped

# Files & Paths
airflow_home: /etc/airflow
airflow_dags_folder: "{{ airflow_home }}/dags"
airflow_virtualenv_folder: "{{ airflow_home }}/virtualenv"
airflow_connections_folder: "{{ airflow_home }}/connections"
airflow_logs_folder: "{{ nfs_mount_point }}/logs"
airflow_child_process_log_folder: "{{ airflow_logs_folder }}/scheduler"
airflow_environment_file_folder: /etc/sysconfig
airflow_plugins_dir: "{{ airflow_home }}/plugins"

# S3 assets
airflow_s3_dags_folder:
airflow_s3_connections_folder:
airflow_s3_plugins_dir_folder:

# Allowing playbooks to provide external config files&templates
airflow_extra_conf_path: "{{ playbook_dir }}/files/airflow"
airflow_extra_conf_template_path: "{{ playbook_dir }}/templates/airflow"

# AIRFLOW CONFIGURATION
# ---------------------

airflow_load_examples: False

# The executor class that airflow should use. Choices include
# SequentialExecutor, LocalExecutor, CeleryExecutor
airflow_executor: SequentialExecutor

airflow_parallelism: 32
airflow_dag_concurrency: 16
airflow_dags_are_paused_at_creation: True
airflow_non_pooled_task_slot_count: 128
airflow_max_active_runs_per_dag: 16

airflow_fernet_key:

airflow_donot_pickle: False
airflow_dagbag_import_timeout: 60

airflow_task_runner: StandardTaskRunner

airflow_default_impersonation:
airflow_unit_test_mode: False

airflow_security:
airflow_secure_mode: False

airflow_task_log_reader: task
airflow_enable_xcom_pickling: True
airflow_killed_task_cleanup_time: 60
airflow_dag_run_conf_overrides_params: False
airflow_worker_precheck: False

airflow_plugins_folder: "{{ airflow_home }}/plugins"

# REMOTE LOGS
airflow_remote_logging: False
airflow_remote_base_log_folder:
airflow_remote_log_conn_id:
airflow_encrypt_s3_logs: False

airflow_hostname_callable: socket:getfqdn
airflow_dag_processor_manager_log_location: "{{ airflow_logs_folder }}/dag_processor_manager/dag_processor_manager.log"

# DB
airflow_database_conn: sqlite:////etc/airflow/airflow.db
airflow_database_pool_size: 5
airflow_database_pool_recycle: 2000
airflow_sql_engine_encoding: utf-8
airflow_sql_alchemy_pool_enabled: True
airflow_sql_alchemy_reconnect_timeout: 300

# CLI
airflow_cli_api_client: airflow.api.client.local_client
airflow_cli_api_endpoint_url: http://localhost:8080

# API
airflow_auth_backend: airflow.api.auth.backend.default

# Lineage
airflow_lineage_backend:

# SASL
airflow_atlas_sasl_enabled: False
airflow_atlas_host:
airflow_atlas_port: 21000
airflow_atlas_username:
airflow_atlas_password:

# WEBSERVER
airflow_webserver_base_url: http://localhost:8080
airflow_webserver_host: 0.0.0.0
airflow_webserver_port: 8080
airflow_webserver_workers: 4
airflow_webserver_worker_timeout: 120
airflow_webserver_ssl_cert:
airflow_webserver_ssl_key:
airflow_webserver_worker_refresh_batch_size: 1
airflow_webserver_worker_refresh_interval: 30
airflow_webserver_secret_key: temporary_key
airflow_webserver_worker_class: sync
airflow_webserver_expose_config: False
airflow_webserver_filter_by_owner: False
airflow_webserver_owner_mode: user
airflow_webserver_dag_orientation: LR
airflow_webserver_demo_mode: False
airflow_webserver_log_fetch_timeout_sec: 5
airflow_webserver_hide_paused_dags_by_default: False
airflow_webserver_dag_default_view: tree
airflow_webserver_page_size: 100
airflow_webserver_rbac: False
airflow_webserver_navbar_color: "#007A87"
airflow_webserver_default_dag_run_display_number: 25
airflow_webserver_enable_proxy_fix: False

# DASK
airflow_dask_cluster_address: 127.0.0.1:8786
airflow_dask_tls_ca:
airflow_dask_tls_cert:
airflow_dask_tls_key:

## Webserver Authentication (http://pythonhosted.org/airflow/security.html#web-authentication)

# Choices of auth_backend include:
# - airflow.contrib.auth.backends.password_auth
# - airflow.contrib.auth.backends.ldap_auth
# - airflow.contrib.auth.backends.github_enterprise_auth
# - airflow.contrib.auth.backends.google_auth
# - others? :)
airflow_webserver_authenticate: False
airflow_webserver_auth_backend:


# OAUTH (only applies if airflow_webserver_auth_backend == "airflow.contrib.auth.backends.google_auth")
airflow_oauth_google_client_id:
airflow_oauth_google_client_secret:
airflow_oauth_google_oauth_callback_route: "/oauth2callback"
airflow_oauth_google_oauth_domain:

# Operators
airflow_operator_default_owner: Airflow
airflow_operator_default_cpus: 1
airflow_operator_default_ram: 512
airflow_operator_default_disk: 512
airflow_operator_default_gpus: 0

# HIVE
airflow_hive_default_hive_mapred_queue:

# LDAP (only applies if airflow_webserver_auth_backend == "airflow.contrib.auth.backends.ldap_auth")
airflow_ldap_uri:
airflow_ldap_user_filter:
airflow_ldap_user_name_attr:
airflow_ldap_group_member_attr: memberOf
airflow_ldap_superuser_filter:
airflow_ldap_data_profiler_filter:
airflow_ldap_bind_user:
airflow_ldap_bind_password:
airflow_ldap_basedn:
airflow_ldap_cacert:
airflow_ldap_search_scope:

# MAIL
airflow_email_backend: airflow.utils.email.send_email_smtp

# SMTP
airflow_smtp_host:
airflow_smtp_starttls: True
airflow_smtp_ssl: False
airflow_smtp_port: 587
airflow_smtp_mail_from: airflow@airflow.com
airflow_smtp_user:
airflow_smtp_passwd:

# SCHEDULER
airflow_scheduler_job_heartbeat_sec: 5
airflow_scheduler_heartbeat_sec: 5
airflow_scheduler_run_duration: -1
airflow_scheduler_min_file_process_interval: 60
airflow_scheduler_dag_dir_list_interval: 300
airflow_scheduler_print_stats_interval: 30
airflow_scheduler_zombie_task_threshold: 300
airflow_scheduler_catchup_by_default: True
airflow_scheduler_max_threads: 2
airflow_scheduler_authenticate: False
airflow_scheduler_health_check_threshold: 30
airflow_scheduler_max_tis_per_query: 300
airflow_scheduler_use_job_schedule: True

## STASTD
airflow_statsd_on: False
airflow_statsd_host: localhost
airflow_statsd_port: 8125
airflow_statsd_prefix: airflow

# CELERY
airflow_celery_app_name: airflow.executors.celery_executor
airflow_worker_concurrency: 16
airflow_celery_worker_log_server_port: 8793
airflow_celery_broker_url: sqla+mysql://airflow:airflow@localhost:3306/airflow
airflow_celery_result_backend: db+mysql://airflow:airflow@localhost:3306/airflow
airflow_celery_default_queue: default
airflow_celery_config_options: airflow.config_templates.default_celery.DEFAULT_CELERY_CONFIG
airflow_celery_ssl_active: False
airflow_celery_ssl_key:
airflow_celery_ssl_cert:
airflow_celery_ssl_cacert:

# FLOWER
airflow_flower_basic_auth:
airflow_flower_host: 0.0.0.0
airflow_flower_port: 5555

# MESOS
airflow_mesos_master_host: localhost:5050
airflow_mesos_framework_name: Airflow
airflow_mesos_task_cpu: 1
airflow_mesos_task_memory: 256
airflow_mesos_checkpoint: False
airflow_mesos_authenticate: False

# KERBEROS
airflow_kerberos_ccache: /tmp/airflow_krb5_ccache
airflow_kerberos_principal: airflow
airflow_kerberos_reinit_frequency: 3600
airflow_kerberos_kinit_path: kinit
airflow_kerberos_keytab: airflow.keytab

# GITHUB ENTEPRISE
airflow_github_enterprise_api_rev: v3

# GIT
airflow_git_repo:
airflow_git_branch:
airflow_git_user:
airflow_git_password:
airflow_git_subpath:
airflow_git_sync_root: /git
airflow_git_sync_dest: repo
airflow_git_dags_folder_mount_point:
airflow_git_sync_container_repository: gcr.io/google-containers/git-sync-amd64
airflow_git_sync_container_tag: v2.0.5
airflow_git_sync_init_container_name: git-sync-clone

# ADMIN
airflow_admin_hide_sensitive_variable_fields: True

# KUBERNETES
airflow_docker_image_slave: puckel/docker-airflow
airflow_kubernetes_worker_container_repository:
airflow_kubernetes_worker_container_tag:
airflow_kubernetes_worker_container_image_pull_policy: IfNotPresent
airflow_kubernetes_delete_worker_pods: True
airflow_kubernetes_namespace: default
airflow_kubernetes_airflow_configmap:
airflow_kubernetes_dags_in_image: False
airflow_kubernetes_dags_volume_subpath:
airflow_kubernetes_dags_volume_claim:
airflow_kubernetes_logs_volume_subpath:
airflow_kubernetes_logs_volume_claim:
airflow_kubernetes_dags_volume_host:
airflow_kubernetes_logs_volume_host:
airflow_kubernetes_worker_service_account_name:

airflow_kubernetes_image_pull_secrets:
airflow_kubernetes_gcp_service_account_keys:
airflow_kubernetes_in_cluster: True
airflow_kubernetes_affinity:
airflow_kubernetes_tolerations:


# ELASTICSEARCH
airflow_elasticsearch_host:
