---
- name: Import Elastic RPM repo key
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Add Elastic yum repo
  copy: src=elastic.repo dest=/etc/yum.repos.d/elastic.repo

- name: Install filebeat 
  yum: name=filebeat state=latest

- name: Adds filebeat to startup
  command: "chkconfig --add filebeat"

- name: Create filebeat config 
  template: src=filebeat.yml.template dest=/etc/filebeat/filebeat.yml

- name: Install logstash
  yum: name=logstash-2.0.0-1 state=present

- name: Install logstash-output-kinesis plugin 
  command: "/opt/logstash/bin/plugin install logstash-output-kinesis"

- name: Update core logstash-input-beats plugin
  command: "echo Y | /opt/logstash/bin/plugin update logstash-input-beats"

- name: Create logstash config 
  template: src=filebeat-kinesis-exporter.conf.template dest=/etc/logstash/conf.d/filebeat-kinesis-exporter.conf
