---
- name: Upgrade packaging
  pip:
    name: "packaging"
    state: "latest"
    executable: pip3

- name: Install whisperx dependencies
  pip:
    name:
     - torch==2.0.0
     - torchvision==0.15.1
     - torchaudio==2.0.1
    executable: pip3
    extra_args: "--index-url https://download.pytorch.org/whl/cu118"

- name: Install whisperx
  pip:
    name: whisperx
    executable: pip3

- name: Download model fetch script
  get_url:
      url: "https://raw.githubusercontent.com/guardian/transcription-service/refs/heads/add-whisperx-support/scripts/download_whisperx_models.py"
      dest: "/tmp/download_whisperx_models.py"
      mode: "0755"

- name: Download whisperx models
  command: "python3 /tmp/download_whisperx_models.py --whisper-models --diarization-models --torch-align-models --huggingface-token {{ huggingface_token }}"
  become: yes
  become_user: ubuntu
