---
- name: Upgrade packaging
  pip:
    name: "packaging"
    state: "latest"
    executable: pip3

- name: Install whisperx dependencies
  pip:
    name:
     - torch==2.0.0
     - torchaudio==2.0.1
    executable: pip3
    extra_args: "--index-url https://download.pytorch.org/whl/cu118"

- name: Install whisperx
  pip:
    name: "{{ whisperx_package | default('whisperx') }}"
    executable: pip3

- name: Simple GET operation
  amazon.aws.s3_object:
    bucket: amigo-data-prod
    object: /deploy/PROD/whisperx-model-fetch/download_whisperx_models.py
    dest: /tmp/download_whisperx_models.py
    mode: get

- name: Download whisperx models
  command: "python3 /tmp/download_whisperx_models.py --whisper-models --diarization-models --torch-align-models --huggingface-token {{ huggingface_token }}"
  become: yes
  become_user: ubuntu
