#!/usr/bin/env bash

set -e

# must be done first as sbt uses the CFN template that is generated
(
 cd cdk
 npm ci
 npm run lint
 npm test
 npm run synth
)

sbt clean scalafmtSbtCheck scalafmtCheckAll compile test riffRaffUpload
