#!/usr/bin/env bash

set -e

(
 cd cdk
 npm ci
 npm run lint
 npm test
 npm run synth
)

sbt clean scalafmtSbtCheck scalafmtCheckAll compile test

# Create debian package of AMIgo Play app
sbt "Debian / packageBin"

# Create zip file of imageCopier lambda
sbt "project imageCopier" "dist"
mv imageCopier/target/universal/imagecopier.zip imageCopier/target/universal/image-copier.zip