#!/usr/bin/env bash
# To set up required resources in a newly-created dev container.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

npm install
npx playwright install --with-deps chromium
