---
- file: path=/opt/features/friendly-hostnames state=directory mode=0755

- name: Copy friendly hostnames
  copy: src=hostnames.txt dest=/opt/features/friendly-hostnames/hostnames.txt mode="a+r"

- name: Copy script for assigning hostnames and make executable
  copy: src=set-hostname.sh dest=/opt/features/friendly-hostnames/set-hostname.sh mode="a+x"
