---
- name: install build-essential
  apt:
    name:
    - build-essential
    state: present

- name: Clone whisper, clone and compile whisper.cpp
  shell: |
    set -e
    mkdir -p {{ target_dir }}
    cd {{ target_dir }}
    echo "cloning"
    git clone --quiet https://github.com/openai/whisper
    git clone --quiet https://github.com/ggerganov/whisper.cpp.git
    cd whisper.cpp
    git reset --hard {{ whisper_cpp_commit_hash }}
    echo "compiling"
    make
    exit 0

- name: Download models and set permissions
  shell: |
    cd {{ target_dir }}/whisper.cpp
    bash models/download-ggml-model.sh {{ item }}
    chown ubuntu ./ --recursive
    exit 0
  loop: "{{ whisper_models }}"

- name: Download and convert medium distilled model
  shell: |
    set -e
    cd {{ target_dir }}/whisper.cpp/models
    git clone https://huggingface.co/distil-whisper/distil-medium.en
    pip3 install torch numpy transformers
    python3 ./convert-h5-to-ggml.py ./distil-medium.en/ {{ target_dir }}/whisper .
    mv ggml-model.bin ggml-medium.en-distil.bin

- name: Install whisper.cpp
  shell: |
    ln -s /opt/whisper/whisper.cpp/main /usr/bin/whisper

  args:
    executable: /bin/bash
