---
- name: install build-essential
  apt:
    name:
    - build-essential
    state: present

- name: Clone and compile whisper.cpp
  shell: |
    set -e
    mkdir -p {{ target_dir }}
    cd {{ target_dir }}
    echo "cloning"
    git clone --quiet https://github.com/ggerganov/whisper.cpp.git
    cd whisper.cpp
    git reset --hard {{ whisper_cpp_commit_hash }}
    echo "downloading models"
    bash models/download-ggml-model.sh medium >
    bash models/download-ggml-model.sh small >
    bash models/download-ggml-model.sh base >
    echo "compiling"
    make
    cd {{ target_dir }}
    chown ubuntu ./ --recursive
    exit 0

- name: Install whisper.cpp
  shell: |
    ln -s /opt/whisper/whisper.cpp/main /usr/bin/whisper

  args:
    executable: /bin/bash
