---
- name: install build-essential
  apt:
    name:
    - build-essential
    state: present

- name: Clone and compile whisper.cpp
  shell: |
    set -e
    mkdir -p {{ target_dir }}
    cd {{ target_dir }}
    echo "cloning"
    git clone --depth 1 --branch v1.4.0 --quiet https://github.com/ggerganov/whisper.cpp.git
    cd whisper.cpp
    echo "downloading model"
    bash models/download-ggml-model.sh large > /dev/null
    bash models/download-ggml-model.sh medium > /dev/null
    bash models/download-ggml-model.sh small > /dev/null
    bash models/download-ggml-model.sh base > /dev/null
    echo "compiling"
    make
    cd {{ target_dir }}
    chown ubuntu ./ --recursive
    exit 0

- name: Install whisper.cpp
  shell: |
    ln -s /opt/whisper/whisper.cpp/main /usr/bin/whisper

  args:
    executable: /bin/bash
