---

# Note: Only Ubuntu versions pre 24.04 have the old td-agent-bit package available
# Note: for Ubuntu versions 24.04 and above the package has been renamed to fluent-bit
- name: Set fluentbit package name
  set_fact:
    fluentbit: "{{ 'td-agent-bit' if ( ansible_distribution_major_version|int <= 22 ) else 'fluent-bit' }}"

- name: Setup target directory
  file:
    path: /var/lib/cloud/scripts/per-instance
    state: directory
  when:
    - ansible_os_family == "Debian"

- name: Install instance-tag-discovery
  shell: |
    NAME=instance-tag-discovery
    /usr/local/bin/aws s3 cp s3://{{ dist_bucket }}/deploy/PROD/$NAME/$NAME-linux-{{ deb_arch }} /var/lib/cloud/scripts/per-instance/00-$NAME
    chmod +x /var/lib/cloud/scripts/per-instance/00-$NAME
  when:
    - ansible_os_family == "Debian"

- name: Install devx-logs
  shell: |
    NAME=devx-logs
    /usr/local/bin/aws s3 cp s3://{{ dist_bucket }}/deploy/PROD/$NAME/$NAME-linux-{{ deb_arch }} /var/lib/cloud/scripts/per-instance/01-$NAME
    chmod +x /var/lib/cloud/scripts/per-instance/01-$NAME
  when:
    - ansible_os_family == "Debian"

# Note, this is required to ensure we start Fluentbit *after* updating the config.
- name: Add start Fluentbit script
  shell: |
    NAME=start-fluentbit
    printf '#!/bin/bash\nsystemctl start {{ fluentbit }}.service' > /var/lib/cloud/scripts/per-instance/02-$NAME
    chmod +x /var/lib/cloud/scripts/per-instance/02-$NAME
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_major_version|int < 24
    - start_fluentbit

- name: Remove syslog output
  shell: |
    NAME=remove-syslog-output
    sudo sh -c 'echo ForwardToSyslog=no >> /etc/systemd/journald.conf'
    sudo systemctl force-reload systemd-journald
  when:
    - ansible_os_family == "Debian"
