Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"
  #config.vm.box = "centos/7"

  config.ssh.insert_key = false

  # For some reason when tried, is sometimes needed with redhat images. Ubuntu and centos seem fine
  # config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |v|
   v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provision "ansible_local" do |ansible|
    ansible.install_mode = "pip" # Ubuntu is fine without that. Redhat prefers it.
    ansible.verbose = "v" # or "vv", "vvv", "vvvv"
    ansible.playbook = "playbook.yaml"
    ansible.extra_vars = "extra-vars.yaml"
  end
end