---
- name: Uninstall ubuntu docker
  apt:
    name: docker docker-engine docker.io
    state: absent
    force: yes

- name: Install required packages
  apt: 
    name:
    - apt-transport-https
    - ca-certificates
    - openssl
    update_cache: yes
    state: present
    force: yes

- name: Add repo key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker.io repo
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable' state=present
  when: ansible_architecture == "x86_64"

- name: Add docker.io repo
  apt_repository: repo='deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable' state=present
  when: ansible_architecture == "aarch64"

- name: Install docker
  apt:
    name: docker-ce={{ version }}~ubuntu*
    update_cache: yes
    state: present

# See https://docs.docker.com/engine/install/linux-postinstall/ for why we're doing these steps
- name: Create docker group
  group:
    name: docker

- name: Add ubuntu user to docker group
  user:
      name: ubuntu
      groups: docker
      append: yes
  when: ansible_distribution == "Ubuntu"