---

- name: Airflow | Copy gunicorn logrotate config
  template:
    src: etc/logrotate.d/gunicorn-logrotate.j2
    dest: /etc/logrotate.d/airflow
    mode: 0644
    owner: root
    group: root

- name: Airflow | Copy basic airflow config file
  template:
    src: "etc/airflow/airflow.cfg.j2"
    dest: "{{ airflow_home }}/airflow.cfg"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  register: airflow_config

- name: Airflow | Setting python virtualenv
  template:
    src: "home/airflow/bash_profile.j2"
    dest: "/home/airflow/.bash_profile"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0644

- name: Airflow | Create path for configuration files
  file:
    path: "{{ airflow_environment_file_folder }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Copy Environment File
  template:
    src: etc/sysconfig/airflow-environment-file.j2
    dest: "{{ airflow_environment_file_folder }}/airflow"
    mode: 0644
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Copy Daemon scripts
  template:
    src: "lib/systemd/system/{{ item.key }}.service.j2"
    dest: /lib/systemd/system/{{ item.key }}.service
    mode: 0644
  with_dict: "{{ airflow_services }}"
  when: item.value.configure
