---

- name: Airflow | Ensure airflow directories structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    recurse: True
  with_items:
    - "{{ airflow_logs_folder }}"
    - "{{ airflow_child_process_log_folder }}"
    - "{{ airflow_dags_folder }}"
    - "{{ airflow_connections_folder }}"
    - "{{ airflow_plugins_folder }}"
    - "{{ airflow_plugins_dir }}"
    - "{{ airflow_virtualenv_folder }}"

- name: Airflow | Copy gunicorn logrotate config
  template:
    src: etc/logrotate.d/gunicorn-logrotate.j2
    dest: /etc/logrotate.d/airflow
    mode: 0644
    owner: root
    group: root

- name: Airflow | Copy basic airflow config file
  template:
    src: "etc/airflow/airflow.cfg.j2"
    dest: "{{ airflow_home }}/airflow.cfg"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  register: airflow_config
