---

- name: Airflow | Configuring service
  systemd:
    name: "{{ item.key }}"
    state: "{{ item.value.state }}"
    enabled: "{{ item.value.enabled }}"
    daemon_reload: yes
  with_dict: "{{ airflow_services }}"
  when: item.value.configure
  changed_when: false
