---

- name: Support | Ensure directories structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ nfs_mount_point }}"
  when: nfs_mount_enabled | bool

- name: Support | Mount EFS
  mount:
    path: "{{ nfs_mount_point }}"
    src: "{{ nfs_mount_id }}"
    fstype: efs
    opts: auto,rw,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,x-systemd.idle-timeout=60min,noatime,nodiratime,noac,nocto,_netdev
    state: present
  when: nfs_mount_enabled | bool

- name: Support | update templates
  template:
    src: "{{ item }}"
    dest: "/{{ item | replace('.j2', '') }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - usr/local/bin/airflow-add-connection.sh.j2
    - usr/local/bin/airflow-update-dags.sh.j2
    - usr/local/bin/airflow-update-connections.sh.j2

- name: Support | Adding autoscaling group mutex scripts
  template:
    src: "{{ item }}"
    dest: "/{{ item | replace('.j2', '') }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - usr/local/sbin/airflow-scheduler-mutex.sh.j2
    - usr/local/sbin/autoscaling-ensure-one-instance.sh.j2

- name: Support | environment
  template:
    src: "{{ item }}"
    dest: "/{{ item | replace('.j2', '') }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - etc/sudoers.d/airflow.j2
    - etc/profile.d/airflow_python_libs.sh.j2

- name: Support | Add ulimits support to pam sudo
  blockinfile:
    dest: /etc/pam.d/sudo
    block: |
      # BEGIN ANSIBLE MANAGED BLOCK
      session     required    pam_limits.so
      # END ANSIBLE MANAGED BLOCK

- name: Support | Bump ulimits
  blockinfile:
    dest: /etc/security/limits.conf
    block: |
      # BEGIN ANSIBLE MANAGED BLOCK
      {{ airflow_user }}    -    nofile    16384
      {{ airflow_user }}    -    stack     16384
      {{ airflow_user }}    -    nproc     16384
      # END ANSIBLE MANAGED BLOCK
