---

- name: Support | Ensure directories structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ nfs_mount_point }}"
  when: nfs_mount_enabled

- name: Support | Mount EFS
  mount:
    path: "{{ nfs_mount_point }}"
    src: "{{ nfs_mount_id }}"
    fstype: efs
    opts: rw,auto,_netdev
    state: present
  when: nfs_mount_enabled

- name: Support | update templates
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | replace('.j2', '') }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - airflow-add-connection.sh.j2
    - airflow-update-dags.sh.j2
    - airflow-update-connections.sh.j2

- name: Support | Adding autoscaling group mutex scripts
  template:
    src: "{{ item }}"
    dest: "/usr/local/sbin/{{ item | replace('.j2', '') }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - airflow-scheduler-mutex.sh.j2
    - autoscaling-ensure-one-instance.sh.j2

- name: Support | sudoers
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item | replace('.j2', '') }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - sudoers.d/airflow.j2
