name: CI
on:
  pull_request:
    branches-ignore:
      - dependency-updates
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read

      # These permissions are required by guardian/actions-riff-raff...
      id-token: write # ...to exchange an OIDC JWT ID token for AWS credentials
      pull-requests: write #...to comment on PRs
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4 # This is required by cdk
        with:
          cache: 'npm'
          cache-dependency-path: 'cdk/package-lock.json'
          node-version-file: '.nvmrc'
      - uses: guardian/setup-scala@v1
      - name: Seed build number from TeamCity
        run: |
          LAST_TEAMCITY_BUILD=3006
          echo BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD )) >> $GITHUB_ENV
      - run: ./script/ci
      - uses: guardian/actions-riff-raff@v4
        with:
          projectName: tools::amigo
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          buildNumber: ${{ env.BUILD_NUMBER }}
          configPath: riff-raff.yaml
          contentDirectories: |
            cloudformation:
              - cdk/cdk.out/AMIgo-CODE.template.json
              - cdk/cdk.out/AMIgo-PROD.template.json
            amigo:
              - target/amigo_1.0-latest_all.deb
            imagecopier:
              - imageCopier/target/universal/image-copier.zip
