name: Create batch dependency update PR

on:
  schedule:
    - cron: "35 10 1 * *"
  # Provide support for manually triggering the workflow via GitHub.
  workflow_dispatch:

jobs:
  pr-tracking-branch:
    name: Open a PR from dependency-updates targeting main
    uses: guardian/.github/.github/workflows/pr-batching_pr-tracking-branch-to-default.yml@v1.0.1
