name: Combine PRs

on:
  schedule:
    - cron: "30 7 * * 1" # Weekly on a Monday at 7:30am UTC
  workflow_dispatch: # allows you to manually trigger the workflow

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.1.0
        with:
          pr_title: "chore(deps): Weekly dependency updates"
          pr_body_header: Weekly dependency updates
          min_combine_number: 1
          branch_regex: ".*"
          select_label: dependencies
